import type { Express } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import { api } from "@shared/routes";
import { z } from "zod";

const SEED_QUESTIONS = [
  { source: "Questions.pdf | Q.129", text: "Your Dataproc cluster runs in a single Virtual Private Cloud (VPC) network in a single subnet with range 172.16.20.128/25. There are no private IP addresses available in the VPC network. You want to add new VMs to communicate with your cluster using the minimum number of steps. What should you do?", options: ["Modify the existing subnet range to 172.16.20.0/24.", "Create a new Secondary IP Range in the VPC.", "Create a new VPC network for the VMs and Peer them.", "Create a new VPC network with subnet 172.32.0.0/16 and Peer."], correctAnswer: 0, rationale: "You can expand the primary IP range of a subnet without downtime. Moving /25 to /24 doubles the IPs." },
  { source: "Premium.pdf | Q.140", text: "You are given a project with a single VPC and a single subnetwork in us-central1. There is a Compute Engine instance hosting an app in this subnet. You need to deploy a new instance in europe-west1. This new instance needs access to the application via private IP. You want to follow Google-recommended practices. What should you do?", options: ["Create a subnetwork in the same VPC, in europe-west1.", "Create a VPC and subnet in europe-west1 and Peer.", "Create a subnetwork in europe-west1 and use Cloud VPN.", "Create a VPC in europe-west1 and use an Internal LB."], correctAnswer: 0, rationale: "VPCs are global. You just add a new regional subnet to the existing VPC and they can talk via private IP by default." },
  { source: "Questions.pdf | Q.164", text: "You are designing a new VPC network that will route traffic to networks in your company's private data center. The data center team requires you to use a routing protocol that can dynamically fail over if there is a link failure in the data center. Which routing protocol should you use?", options: ["BGP", "RIP", "OSPF", "Static routing"], correctAnswer: 0, rationale: "Cloud Router uses BGP (Border Gateway Protocol) for dynamic routing over VPN/Interconnect." },
  { source: "Premium.pdf | Q.91", text: "Your company has a 3-tier solution running on Compute Engine. Tier #1 must communicate with Tier #2, and Tier #2 with Tier #3 on TCP 8080. Each tier has a service account associated with its instances. What should you do?", options: ["Create ingress firewall rules using Source/Target Service Accounts.", "Create ingress rules using IP ranges.", "Create egress rules using Service Accounts.", "Create egress rules using IP ranges."], correctAnswer: 0, rationale: "Service Accounts are the best practice for identifying 'Tiers' of applications in firewall rules, rather than brittle IP ranges." },
  { source: "Questions.pdf | Q.197", text: "Your organization has a 3-tier web application deployed in the same network on Google Cloud Platform. Each tier scales independently. Network traffic should flow through web to API to database. Traffic should NOT flow between web and database. How should you configure the network?", options: ["Add tags to each tier and set up firewall rules to allow the desired traffic flow.", "Add each tier to a different subnetwork.", "Set up software-based firewalls on individual VMs.", "Add tags to each tier and set up routes."], correctAnswer: 0, rationale: "Firewall rules using Tags (or Service Accounts) allow you to micro-segment traffic within the same network." },
  { source: "Questions.pdf | Q.166", text: "You work with a video rendering application that publishes small tasks to Pub/Sub. Each task takes less than 1 hour to complete. You need to minimize rendering costs. What should you do?", options: ["Deploy the application as a managed instance group with Preemptible VMs.", "Deploy as MIG with Committed Use Discount.", "Deploy as MIG with Standard VMs.", "Deploy as MIG with Preemptible VMs and Committed Use Discount."], correctAnswer: 0, rationale: "Preemptible VMs are cheapest. Tasks < 1 hour fit well within the 24h limit and interruption risk." },
  { source: "Questions.pdf | Q.245", text: "Which of the following is a virtual machine instance that can be terminated by Compute Engine without warning?", options: ["A preemptible VM", "A shared-core VM", "A high-cpu VM", "A standard VM"], correctAnswer: 0, rationale: "Preemptible (or Spot) VMs can be reclaimed by Google at any time." },
  { source: "Questions.pdf | Q.96", text: "Your company runs its Linux workloads on Compute Engine instances. Your company will be working with a new operations partner that does not use Google Accounts. You need to grant access to the instances to your operations partner so they can maintain the installed tooling. What should you do?", options: ["Enable Cloud IAP and add them as Tunnel User.", "Tag instances and create a firewall rule allowing TCP 22 from the partner's IP.", "Set up Cloud VPN.", "Ask the partner to generate SSH key pairs and add public keys to the VM instances."], correctAnswer: 1, rationale: "If they don't have Google Accounts, they can't use IAP (which requires IAM). You must fallback to IP-based firewall allowlisting for SSH." },
  { source: "Premium.pdf | Q.128", text: "You need to host an application on a Compute Engine instance in a project shared with other teams. You want to prevent other teams from accidentally causing downtime on that application by deleting it. Which feature should you use?", options: ["Enable deletion protection on the instance.", "Use a Shielded VM.", "Use a Preemptible VM.", "Use a sole-tenant node."], correctAnswer: 0, rationale: "Deletion Protection is the specific flag to prevent accidental API deletion calls." },
  { source: "Questions.pdf | Q.144", text: "You have a Compute Engine instance hosting an application used between 9 AM and 6 PM on weekdays. You want to back up this instance daily for disaster recovery purposes. You want to keep the backups for 30 days. You want the Google-recommended solution with the least management overhead. What should you do?", options: ["In the Cloud Console, go to Disks and configure a Snapshot Schedule.", "Create a Cloud Function to snapshot daily.", "Create a bash script on the instance.", "Update instance metadata with snapshot-schedule."], correctAnswer: 0, rationale: "Snapshot Schedules are the native, managed way to handle backup/retention." },
  { source: "Questions.pdf | Q.246", text: "Regarding Cloud Storage: which of the following allows for time-limited access to buckets and objects without a Google account?", options: ["Signed URLs", "gsutil", "Single sign-on", "Temporary Storage Accounts"], correctAnswer: 0, rationale: "Signed URLs give anyone with the link access for a specific time duration." },
  { source: "Premium.pdf | Q.114", text: "You are using Container Registry to centrally store your company's container images. In another project, you want to create a GKE cluster. You want to ensure that Kubernetes can download images from Container Registry. What should you do?", options: ["Grant Storage Object Viewer IAM role to the service account used by Kubernetes nodes.", "Configure ACLs on each image.", "Create a P12 key.", "Choose 'Allow full access to all Cloud APIs'."], correctAnswer: 0, rationale: "Images are stored in GCS (for GCR). The GKE Node Service Account needs Reader/Viewer access to that storage bucket." },
  { source: "Questions.pdf | Q.231", text: "If you do not grant a user named Bob permission to access a Cloud Storage bucket, but then use an ACL to grant access to an object inside that bucket to Bob, what will happen?", options: ["Bob will be able to access the object.", "Bob will access all objects.", "Bob cannot access the object because he lacks bucket access.", "It is not possible to grant access to an object if bucket access is missing."], correctAnswer: 0, rationale: "Legacy ACLs allow granular object access even if bucket-level IAM is missing (unless Uniform Bucket Level Access is enabled, which disables ACLs. The question implies ACLs are active)." },
  { source: "Questions.pdf | Q.188", text: "The hospital requires that patient information stored in Cloud Storage buckets not leave the geographic areas in which the buckets are hosted. You need to ensure that information stored in Cloud Storage buckets in 'europe-west2' does not leave that area. What should you do?", options: ["Enable VPC Service Controls and create a service perimeter.", "Encrypt the data on-premises.", "Assign IAM storage.objectViewer only to authorized users.", "Create an ACL limiting access."], correctAnswer: 0, rationale: "VPC Service Controls (VPCSC) are designed to prevent data exfiltration across boundaries." },
  { source: "Premium.pdf | Q.125", text: "You need to set up a policy so that videos stored in a specific Cloud Storage Regional bucket are moved to Coldline after 90 days, and then deleted after one year. How should you set up the policy?", options: ["Use Object Lifecycle Management with Age conditions.", "Use gsutil rewrite.", "Use a Cloud Function.", "Use Cloud Scheduler."], correctAnswer: 0, rationale: "Lifecycle Management is the native tool for age-based transitions." },
  { source: "Premium.pdf | Q.78", text: "You create a new GKE cluster and want to make sure that it always runs a supported and stable version of Kubernetes. What should you do?", options: ["Enable Node Auto-Upgrades.", "Enable Node Auto-Repair.", "Select the latest available cluster version.", "Select Container-Optimized OS."], correctAnswer: 0, rationale: "Auto-upgrades keep the nodes in sync with the control plane patch version." },
  { source: "Questions.pdf | Q.159", text: "You have a Kubernetes cluster with 1 node-pool. The cluster receives a lot of traffic and needs to grow. You decide to add a node. What should you do?", options: ["Use 'gcloud container clusters resize'.", "Use 'kubectl container clusters resize'.", "Edit the managed instance group directly.", "Enable autoscaling on the instance group."], correctAnswer: 0, rationale: "gcloud is the tool for infrastructure (nodes). kubectl is for k8s objects (pods)." },
  { source: "Premium.pdf | Q.85", text: "You are creating a GKE cluster with cluster autoscaler enabled. You need to make sure that each node of the cluster will run a monitoring pod that sends container metrics to a third-party solution. What should you do?", options: ["Deploy the monitoring pod in a DaemonSet.", "Deploy in a StatefulSet.", "Reference the pod in a Deployment.", "Use a cluster initializer."], correctAnswer: 0, rationale: "DaemonSets run one pod per node, even as nodes scale up/down." },
  { source: "Premium.pdf | Q.51", text: "Your existing application running in GKE consists of multiple pods running on four GKE n1-standard-2 nodes. You need to deploy additional pods requiring n2-highmem-16 nodes without any downtime. What should you do?", options: ["Create a new Node Pool with n2-highmem-16 nodes.", "Upgrade the existing cluster.", "Create a new cluster.", "Use Vertical Pod Autoscaling."], correctAnswer: 0, rationale: "Node Pools allow you to mix machine types in a single cluster." },
  { source: "Questions.pdf | Q.154", text: "A team of data scientists infrequently needs to use a GKE cluster. They require GPUs for some long-running, non-restartable jobs. You want to minimize cost. What should you do?", options: ["Create a node pool with preemptible VMs and GPUs.", "Create a node pool of instances with GPUs and enable autoscaling with min size 0.", "Enable node auto-provisioning.", "Create a VerticalPodAutoscaler."], correctAnswer: 1, rationale: "You can't use Preemptible for 'non-restartable' jobs (they get killed). So you use a standard pool but autoscale it to 0 when not in use." },
  { source: "Premium.pdf | Q.27", text: "You are using GKE with autoscaling. You want to expose a new application to the public using HTTPS on a public IP. What should you do?", options: ["Create a Kubernetes Ingress.", "Create a Service of type ClusterIP.", "Create a Service of type NodePort and configure DNS.", "Use HAProxy on a node."], correctAnswer: 0, rationale: "Ingress provides Layer 7 HTTP(S) Load Balancing." },
  { source: "Questions.pdf | Q.135", text: "You need to deploy an application packaged in a container image. It exposes an HTTP endpoint and receives very few requests per day. You want to minimize costs. What should you do?", options: ["Deploy on Cloud Run (fully managed).", "Deploy on Cloud Run on GKE.", "Deploy on App Engine Flexible.", "Deploy on GKE."], correctAnswer: 0, rationale: "Cloud Run scales to zero and charges only for request time, perfect for 'few requests'." },
  { source: "Premium.pdf | Q.173", text: "You want to run a single caching HTTP reverse proxy on GCP. It consumes almost no CPU but needs 30GB in-memory cache. You want to minimize cost. How should you run it?", options: ["Run it on Compute Engine with a custom instance type (high memory, low cpu).", "Create a Cloud Memorystore instance.", "Run it on GKE.", "Run it on Cloud Run."], correctAnswer: 0, rationale: "Compute Engine Custom Machine Types allow you to dial up RAM without paying for unnecessary CPU." },
  { source: "Premium.pdf | Q.118", text: "You have a website on App Engine standard. You want 1% of your users to see a new test version. You want to minimize complexity. What should you do?", options: ["Deploy new version and use --splits option.", "Deploy new version and use -migrate.", "Create a new App Engine application.", "Configure a network load balancer."], correctAnswer: 0, rationale: "App Engine traffic splitting is a native feature." },
  { source: "Questions.pdf | Q.224", text: "Which statements about application load testing are true? (Select 2)", options: ["You should test at the maximum load you expect.", "Your load tests should include testing sudden increases in traffic.", "You should test at 50% more than max load.", "It is not necessary to test sudden increases."], correctAnswer: 1, rationale: "Usually A and D (Testing max load and spikes) are the correct pair for reliability." },
  { source: "Premium.pdf | Q.146", text: "Your company has a single sign-on (SSO) identity provider using SAML. You want users to authenticate using your company's SSO. What should you do?", options: ["In Cloud Identity, set up SSO with Google as identity provider.", "In Cloud Identity, set up SSO with third-party identity provider.", "Obtain OAuth 2.0 credentials.", "Create a VPN."], correctAnswer: 1, rationale: "Cloud Identity allows you to configure an external IdP (Identity Provider) for SAML." },
  { source: "Questions.pdf | Q.201", text: "Your company wants to deploy several microservices. Each uses different software libraries. You want to enable developers to keep their dev environment in sync with production. Which technology?", options: ["Containers", "Virtual Machines", "Chef/Puppet", "RPM/DEB"], correctAnswer: 0, rationale: "Containers package dependencies, ensuring dev=prod parity." },
  { source: "Premium.pdf | Q.122", text: "You have a Linux VM that must connect to Cloud SQL. You want to make sure the VM uses a specific service account instead of the default. What should you do?", options: ["Specify the service account under 'Identity and API Access' when creating the VM.", "Download a JSON key and put it in metadata.", "Download a JSON key and save it to ~/.gcloud.", "Grant roles to the default account."], correctAnswer: 0, rationale: "Always attach the identity at the infrastructure level (VM config) rather than managing keys." },
  { source: "Questions.pdf | Q.237", text: "Which of the following is NOT an IAM best practice?", options: ["Use primitive roles by default.", "Grant roles at smallest scope.", "Treat components as separate trust boundaries.", "Restrict service account creation."], correctAnswer: 0, rationale: "Primitive roles (Owner/Editor) are too broad. Use Predefined/Custom." },
  { source: "Premium.pdf | Q.111", text: "You are running BigQuery. A partner company needs access to your dataset. They manage their own GCP project. What should you do?", options: ["Ask the partner to create a Service Account in their project, and grant it access in your project.", "Create a SA in your project and give them the key.", "Create a SA in your project and grant it access.", "Ask them to use their personal Gmails."], correctAnswer: 0, rationale: "Let them own the identity (SA), you own the permission." },
  { source: "Premium.pdf | Q.170", text: "You need to create a Compute Engine instance in a new project that doesn't exist yet. What should you do?", options: ["Create the project, enable API, then create instance.", "Enable API in console, then create.", "Use gcloud with --project flag.", "Look for 'Create In New Project' in console."], correctAnswer: 0, rationale: "You cannot create a resource in a non-existent project. Sequence: Create Project -> Enable API -> Create Resource." },
  { source: "Premium.pdf | Q.176", text: "Your VMs are running in a subnet 255.255.255.240 (/28). The subnet has no more IPs. You need 10 more IPs. Existing VMs must reach new VMs without extra routes. What do you do?", options: ["Use gcloud to expand the IP range.", "Delete and recreate.", "Create a new project.", "Create a new subnet."], correctAnswer: 0, rationale: "Subnet expansion is the only non-destructive way." },
  { source: "Premium.pdf | Q.150", text: "You check the status of deployed pods and notice one is PENDING. What is the most likely cause?", options: ["Cluster resource exhaustion (CPU/RAM).", "Image missing.", "App crashed.", "Firewall blocked."], correctAnswer: 0, rationale: "Pending = Scheduler cannot find a node to place the pod." },
  { source: "Questions.pdf | Q.127", text: "A dev team works with two Cloud Functions (dev/prod). Code is same except for Cloud SQL database values. How should you pass the database value?", options: ["Environment Variables.", "Metadata.", "Service Accounts.", "Timeouts."], correctAnswer: 0, rationale: "Env vars are the standard way to inject config into functions." },
  { source: "Premium.pdf | Q.109", text: "An external auditor needs to review resources in a specific project. Security has enabled Domain Restricted Sharing. What should you do?", options: ["Create a temporary account for the auditor in Cloud Identity and grant Viewer.", "Ask for their Gmail.", "Grant Security Reviewer.", "Grant Browser."], correctAnswer: 0, rationale: "Domain Restricted Sharing prevents granting roles to external emails (Gmail). You must create a user *inside* your domain." },
  { source: "Questions.pdf | Q.198", text: "You set up an autoscaling instance group behind an HTTP(S) LB. You notice VMs are terminating and re-launching every minute. They have no public IP. You verified web response via curl. What is the issue?", options: ["Firewall rule missing for LB health checks.", "Firewall rule missing for source traffic.", "Public IP required.", "Tags missing."], correctAnswer: 0, rationale: "The LB Health Check comes from specific Google ranges (130.211.0.0/22, 35.191.0.0/16). If firewall blocks this, LB thinks VMs are dead and restarts them." },
  { source: "Premium.pdf | Q.38", text: "You have a 5TB AVRO file in Cloud Storage. Analysts proficient only in SQL need access. What is the most cost effective way?", options: ["Create external tables in BigQuery pointing to Cloud Storage.", "Load data into BigQuery.", "Load into Datastore.", "Use Hadoop."], correctAnswer: 0, rationale: "External tables allow querying data *in place* without paying for ingestion/storage in BQ (though query cost applies)." }
];

async function seedDatabase() {
  const existing = await storage.getQuestions();
  if (existing.length === 0) {
    console.log("Seeding database with questions...");
    for (const q of SEED_QUESTIONS) {
      await storage.createQuestion(q);
    }
  }
}

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  // Seed database
  await seedDatabase();

  app.get(api.questions.list.path, async (_req, res) => {
    const questions = await storage.getQuestions();
    res.json(questions);
  });

  app.post(api.attempts.create.path, async (req, res) => {
    try {
      const attemptData = api.attempts.create.input.parse(req.body);
      const attempt = await storage.createAttempt(attemptData);
      res.status(201).json(attempt);
    } catch (e) {
      if (e instanceof z.ZodError) {
        res.status(400).json({ message: "Invalid input", errors: e.errors });
      } else {
        res.status(500).json({ message: "Internal server error" });
      }
    }
  });

  app.get(api.attempts.list.path, async (_req, res) => {
    const attempts = await storage.getAttempts();
    res.json(attempts);
  });

  return httpServer;
}
